/**
* @File Name : ChatController.cls
* @Description :
* @Author :
* @Last Modified By :
* @Last Modified On : May 29, 2025
* @Modification Log :
*==============================================================================
* Ver | Date | Author | Modification
*==============================================================================
* 1.0 | May 29, 2025 |   | Initial Version
**/

public class ChatController {
	@AuraEnabled
	public static void LightningStudio(){
		System.debug('Lightning Studio');
	}
}